POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "danys",
    "password": "12345"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "danys",
    "password": "12345",
    "email": "dany@mail.ru"
}
###
POST http://localhost:3000/users/notes/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA3NDI4OTQsImV4cCI6MTU4MDk1ODg5NH0.taVDAaJ0XenCMFdc9lzlLHKSsfEeZLTxLlTMPdhckZg

{
    "text": "101",
    "title": "101"
}


###

PUT http://localhost:3000/notes/24/tags/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA3NDI4OTQsImV4cCI6MTU4MDk1ODg5NH0.taVDAaJ0XenCMFdc9lzlLHKSsfEeZLTxLlTMPdhckZg

{
    "name": "dans"
}

###

POST http://localhost:3000/notes/22/likes/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA3NDI4OTQsImV4cCI6MTU4MDk1ODg5NH0.taVDAaJ0XenCMFdc9lzlLHKSsfEeZLTxLlTMPdhckZg

{
    "tab": "1"
}

###

GET http://localhost:3000/users/recentEntries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA3NDI4OTQsImV4cCI6MTU4MDk1ODg5NH0.taVDAaJ0XenCMFdc9lzlLHKSsfEeZLTxLlTMPdhckZg

###

GET http://localhost:3000/users/uniqueTags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA3NDI4OTQsImV4cCI6MTU4MDk1ODg5NH0.taVDAaJ0XenCMFdc9lzlLHKSsfEeZLTxLlTMPdhckZg


###

GET http://localhost:3000/users/rating-by-latest-likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnkiLCJzdWIiOjEsImlhdCI6MTU4MDc1MjUyNywiZXhwIjoxNTgwOTY4NTI3fQ.W-xMueCJZXVt-z8BCGiYL23YtDK1AeYyQ_eyrJeAVSo