
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "dany",
    "password": "34a"
}

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "danys",
    "password": "1234a"
}

###
POST http://localhost:3000/products/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpbWEiLCJzdWIiOjU0LCJpYXQiOjE1ODE3OTcwNjksImV4cCI6MTU4MjAxMzA2OX0.YcyOg6zr9WS1mrCkwIm0NDWaHnr-617b27sTFzPWXiI

{
    "name": "danyasdsdsa",
    "avatar": "1234a",
    "description": "asdsadsad",
    "number": 1
}

###

GET http://localhost:3000/products/from-users-cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnkiLCJzdWIiOjYxLCJpYXQiOjE1ODIzMjg2NTIsImV4cCI6MTU4MjU0NDY1Mn0.ZvaUUI0jH124_e3I5UScWr9CBsBIMaP_9wJPDAjTpOA
